variables: 
  PORT_NUMBER: 8888
build-dev:
  stage: build
  only: 
  - dev
  tags:
  - cmon04_tag #36
  variables:
    PROFILE: dev
    BRANCH_GIT : dev
    BUILD_DIR: /data
    
  script: &build_script
  - systemctl stop gunicorn
  - pwd
  - cd ${BUILD_DIR}
  - pwd
  - rm -rf ${BUILD_DIR}/phonetics ${BUILD_DIR}/templates
  - echo ${PROFILE}
  - echo ${BRANCH_GIT}
  - git clone --branch ${BRANCH_GIT} http://${CICD_USER}:${CICD_PASSWORD}@10.101.18.33:10080/3rd-party/phonetics.git
  - cd ${BUILD_DIR}/phonetics
  - git clone http://${CICD_USER}:${CICD_PASSWORD}@10.101.18.33:10080/3rd-party/templates.git
  - pwd
  - mv -f templates/profiles/default/${PROFILE}/configuration.py .
  - cd ${BUILD_DIR}/phonetics
  - rm -rf venv
  - virtualenv --python=python3.6 venv
  - source venv/bin/activate
  - pip3 install -r requirements.txt
  - systemctl start gunicorn
  
build-staging:
  stage: build
  only:
  - master
  tags:
  - phonetics_tag #10.101.15.30
  variables:
    PROFILE: staging
    BRANCH_GIT : master
    BUILD_DIR: /MDM
    
  script: *build_script